parameters:
    environment: ''
    artifactName: ''
    serviceConnection: ''
    webAppName: ''

jobs:
- deployment : 'WebDeploy'
  pool: 
    vmImage: 'ubuntu-latest'
  environment: '$(environment)'
  strategy:
        runOnce:
         deploy:
           steps:
           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: $(artifactName)
               downloadPath: '$(System.ArtifactsDirectory)'
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: $(serviceConnection)
              appType: 'webApp'
              WebAppName: $(webAppName)
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'