parameters:
    environment: ''
    artifactName: ''
    serviceConnection: ''
    webAppName: 'test110'

jobs:
- deployment : 'WebDeploy'
  pool: 
    vmImage: 'ubuntu-latest'
  environment: '$(environment)'
  strategy:
        runOnce:
         deploy:
           steps:
           - script: |
              echo Major: $(webAppName)
              echo Major: $(environment)
              echo Major: $(artifactName)
              echo Major: $(serviceConnection)
           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: '$(artifactName)'
               downloadPath: '$(System.ArtifactsDirectory)'
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webAppName)'
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'