# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  buildConfiguration: 'Release'
  serviceConnection : 'az-serviceprincipal'

stages:
- stage : 'Build' 
  displayName:  'Build, execution des tests et publication'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job : 'Build'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
         command: 'restore'
         projects: '**/*.csproj'
         feedsToUse: 'select'
        displayName: 'restaurer les packages'

      - task: DotNetCoreCLI@2
        inputs:
         command: 'build'
         projects: '**/*.csproj'
         arguments: '--configuration $(buildConfiguration)'
        displayName: 'Génération de la solution'

      - task: DotNetCoreCLI@2
        inputs:
         command: 'test'
         projects: '**/*Tests.csproj'
         arguments: '--configuration $(buildConfiguration)'
        displayName: 'Exécution des tests unitaires'
     
      - task: DotNetCoreCLI@2
        inputs:
         command: 'publish'
         publishWebProjects: true
         arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        displayName: 'Génération du package de publication'

- stage : 'DeployToDev' 
  displayName:  'Déploiment en Dev'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: 'Build'
  jobs:
    - deployment : 'DeployToDev'
      environment: 'h22-developpement'
      strategy:
        runOnce:
         deploy:
           steps:
           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: 'drop'
               downloadPath: '$(System.ArtifactsDirectory)'
             displayName: 'Téléchargement du package'
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: 'webapp-h22-dev-120'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
             displayName: 'déploiment de application'
